apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzVrY21WM2RtbHphRzU1WVd0dmRqcG5hSEJmYjFVemVHbDVNRkJqV0ZwNFQxQXlNMUp2U0VSdlNHcG5TSFo1YzBoSk1FMVdPSGt6IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
