apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzVrY21WM2RtbHphRzU1WVd0dmRqcG5hSEJmU0dkWlpUTklNVzAxT0hsWE5FMVJWRFpUWm1kd1dXbzRkMVZ5UTI5a01rSTBORXRxIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
